### ISSUE TITLE
Error thrown when trying to insert a page-tree. Log says class not found.

### ISSUE THREAD

**Issue by ghost** [NamelessCoder/asynchronous_reference_indexing#1]
I successfully installed (via Composer) and activated the extension on a TYPO3 7.6.14 LTS.

Then, in the page-tree I copied a page-tree (I have recursive levels set to 9*). When I tried to insert I just saw a HTTP 500 code in the browser's Network Inspector. The TYPO3 Log module had the following info:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'NamelessCoder\AsyncReferenceIndexing\DataHandling\DataHandler' not found | Error thrown in file /<path>/vendor/typo3/cms/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 4535. Requested URL: https://<domain>/typo3/index.php?ajaxID=%2Fajax%2Fext-direct%2Froute&namespace=TYPO3.Components.PageTree`

* I suppose it could go all the way to 11 ;-)

**Comment by NamelessCoder** [comment]
Should be fixed with 1.0.1 release - error in composer class loading file not detected due to using manual class loading in local dev. Sorry about that!

**Comment by ghost** [comment]
Seems to be fixed now.
