### ISSUE TITLE
Command controller not available in Scheduler

### ISSUE THREAD

**Issue by ghost** [NamelessCoder/asynchronous_reference_indexing#2]
I wanted to setup the command controller, but when it tried to create an _Extbase CommandController Task_, it wasn't available among the other CommandControllers in the drop-down.

Also, on the command line the list obtained by `./typo3/cli_dispatch.phpsh extbase help` does not show any sign of having recognised async. ref. indexing.

All of the above might be related to Issue 1.

I am running TYPO3 7.6.14 LTS on a Linux system.

**Comment by NamelessCoder** [comment]
Most likely also caused by composer class loading issues in 1.0.0, fixed in 1.0.1. To use the command controller as a Scheduler task you have to select the "Extbase command controller" wrapper task in Scheduler and then configure that task to call the actual command controller.

**Comment by ghost** [comment]
Seems fixed now. I have setup the scheduler and it started running nicely - and kept on going, never stopping (issue coming right up ;-))
