### ISSUE TITLE
Name of the referenceindex:update-command have a collision with a backend-command

### ISSUE THREAD

**Issue by cabi** [NamelessCoder/asynchronous_reference_indexing#21]
The command I run in my shell
`# /var/www/docroot/typo3/sysext/core/bin/typo3`
or 
`# /vendor/bin/typo3`

Then this error occures:
```
Uncaught TYPO3 Exception #1484486383: Command "referenceindex:update" registered by "backend" is already in use
thrown in file /var/www/vendor/typo3/cms/typo3/sysext/core/Classes/Console/CommandRequestHandler.php
in line 150
```

It seams, that the TYPO3 Backend want to register its `referenceindex:update` command. At this time the Command `referenceindex:update` from EXT:async_reference_indexing is already registered.
This throw an Exception and the cli-interface is not usable.

I think the fastest way to fix this is to rename the command to something like 'asyncUpdateCommand'.

This take part with the typo3-cli. With the typo3cms-cli this error doesn't occure ... the last entry wins and no exception is thrown - but one command is lost.

I hope this helps,
Carsten

**Comment by NamelessCoder** [comment]
Which TYPO3 version do you use?

**Comment by cabi** [comment]
Sorry that I forget to mention the TYPO3 version. My bad.

My actual version is 8.7.4

**Comment by cvisys** [comment]
Renaming the class to something different than referenceindex fixes the problem.

**Comment by NamelessCoder** [comment]
Solved by https://github.com/NamelessCoder/asynchronous_reference_indexing/pull/22
