### ISSUE TITLE
Scheduler task never stops

### ISSUE THREAD

**Issue by ghost** [NamelessCoder/asynchronous_reference_indexing#3]
I installed v. 1.0.2 and added a Scheduler task for the reference indexer. I set the task to run every 60 seconds and disallowed simultaneous runs (the cronjob triggering scheduler runs once a minute). I then verified that the task started successfully.

Trouble is, that it doesn't seem to ever stop again, so every minute it get a new entry in the Log module: "[scheduler]: Task is already running and multiple executions are not allowed, skipping! Class: TYPO3\CMS\Extbase\Scheduler\Task, UID: 6"

I went to the DB Check module and ran the refindex re-building from there. I ran for a little more that thirty seconds and then reported: _6180 records from 38 tables were checked/updated. Index Integrity was perfect!_

Since the complete refindex checking takes much less than sixty seconds, I assume that it is the Scheduler task that is something wrong with.

**Comment by NamelessCoder** [comment]
This could very well be a bug in TYPO3 itself, in the "Extbase command controller" task. If you're able to run the CLI command, `./typo3/cli_dispatch.phpsh extbase referenceindex:update` then I'd say that's a clear sign of a problem in scheduler.

**Comment by ghost** [comment]
Seems to have been fixed; tested with v. 1.1.0 on TYPO3 7.6.14. Likely fixed in commit 1798bd049e678f8b00150581c8ef8d84944037f6
